name: netflix_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  reactive_button: ^0.0.9
  flutter_bloc:
  dartz:
  dio:
  logger:
  get_it:
  shared_preferences: ^2.3.3
  flutter_svg:
  fan_carousel_image_slider:
  youtube_player_flutter: 9.0.0
  chewie: ^1.8.5
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/vectors/

